### ISSUE TITLE
getColors()  is not working well.

### ISSUE THREAD

**Issue by GoalPanda** [xxmuaddib/lottie-colorify#7]
![image](https://user-images.githubusercontent.com/73328056/106405440-107ca280-63eb-11eb-8d08-6adce922d4b0.png)

Now I am going to change the specific colors of this Lottie file.
So in order to do this, I need to get whole colors and selector one of them...
But returned colors are all NaN.
But some of my json files are working well..

Please help me

**Comment by xxmuaddib** [comment]
Can you post your JSON?

**Comment by GoalPanda** [comment]
Thanks for your caring.
https://s3.us-east-2.amazonaws.com/animatly.io/Illustrations/json/04.json

and also some other files are not able to change the colors.
But instead, I can get the whole colors of that file.
should I share that files too?
https://s3.us-east-2.amazonaws.com/animatly.io/Illustrations/json/01.json
Thanks.

**Comment by GoalPanda** [comment]
> Can you post your JS
